### ISSUE TITLE
I get the following error when I update to the current version of RedGearCore

### ISSUE THREAD

**Issue by Prometheius** [RedGear/RedGearCore#1]
http://pastebin.com/pkbkuLiu

Time: 2/10/14 1:32 AM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: itemID
        at redgear.core.util.SimpleItem.<init>(SimpleItem.java:36)
        at redgear.core.util.SimpleItem.<init>(SimpleItem.java:44)
        at redgear.geocraft.core.Geocraft.<clinit>(Geocraft.java:39)

**Comment by MagmaSlime123** [comment]
> Fixed with 2.0.3a. Thank you for reporting it.

Delete your stuff if your not updating it. Give it to other people if you won't.
